#!/bin/bash
echo -e "[\e[31m1\e[m] Please enter the filename for the main script in this DIR";
read -p ' :  ' FILENAME;
echo;
echo;
echo -e "[\e[31m1\e[m] Language?";
read -p ' :  ' LANGUAGE;
echo;
echo;
echo -e "[\e[31m1\e[mDescription";
read -p ' :  ' DESCRIPTION;
echo;
echo;
echo -e "[\e[31m1\e[m] Installation instructions";
read -p ' :  ' INSTALL;
echo;
echo;


echo -e "[37;46mＤｉｒｅｃｔｏｒｙ[m" >> .DIR.NFO;
dirs >> .DIR.NFO;
echo >> .DIR.NFO;
echo -e "[37;46mＦｉｌｅｎａｍｅ[m" >> .DIR.NFO;
echo "$FILENAME" >> .DIR.NFO;
echo >> .DIR.NFO;
echo -e "[37;46mＬａｎｇｕａｇｅ[m" >> .DIR.NFO;
echo "$LANGUAGE" >> .DIR.NFO;
echo >> .DIR.NFO;
echo -e "[37;46mＤｅｓｃｒｉｐｔｉｏｎ[m" >> .DIR.NFO;
echo "$DESCRIPTION" >> .DIR.NFO;
echo >> .DIR.NFO;
echo -e "[37;46mＩｎｓｔａｌｌ  ／  Ｓｅｔｕｐ[m" >> .DIR.NFO;
echo "$INSTALL" >> .DIR.NFO;
echo >> .DIR.NFO;
cat ./.DIR.NFO;
unset INSTALL DESCRIPTION FILENAME LANGUAGE;
